version: "3.0"
services:
    db:
      image: mysql:5.7
      ports:
        - "3306:3306"
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: unitTest
        MYSQL_USER: unitTest
        MYSQL_PASSWORD: ""
    php:
        build: ./docker/php
        ports:
            - "9000:9000"
        volumes:
            - "./:/var/www/unitTest"
        links:
            - db
    nginx:
        build: ./docker/nginx
        ports:
            - "80:80"
        links:
            - php
        volumes:
            - php
